# TODO: Use PLD automagic instead of  ./config/autorun.sh
# TODO: Review link_fix.patch:
#	  why extra -lthrift is needed
#	  as all linkinfo about thrift should be in  $(LIBTHRIFT)

Summary:	A high level C++ client for Cassandra
Summary(pl.UTF-8):	Klient Cassandry wyższego poziomu w C++
Name:		libcassandra
Version:	0.2.0.git20110414
Release:	0.2
License:	BSD
Group:		Libraries
# http://beauty.ant.gliwice.pl/PLD/libcassandra-0.2.0.git-20110414.tar.gz
Source0:	http://beauty.ant.gliwice.pl/PLD/%{name}-%{version}.tar.gz
# Source0-md5:	c1f2e536267500c55707f96d341d7297
Patch0:		%{name}-link_fix.patch
URL:		https://github.com/posulliv/libcassandra
BuildRequires:	autoconf
BuildRequires:	automake
BuildRequires:	boost-devel
BuildRequires:	libtool
BuildRequires:	rpmbuild(macros) >= 1.583
BuildRequires:	thrift-devel >= 0.5.0
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
A C++ wrapper library for the interface to cassandra generated by
thrift. This library is based on the Java client hector.

%description -l pl.UTF-8
Biblioteak C++ wokół interfejsu do Cassandry wygnerwoanej przez
thrift. Oparta na Javowym kliencie Hector.


%package devel
Summary:	Header files for libcassandra library
Summary(pl.UTF-8):	Pliki nagłówkowe biblioteki libcassandra
Group:		Development/Libraries
Requires:	%{name} = %{version}-%{release}

%description devel
Header files for libcassandra library.

%description devel -l pl.UTF-8
Pliki nagłówkowe biblioteki libcassandra.


%prep
%setup -q
%patch0 -p1

%build
%{__libtoolize}
%{__aclocal} -I m4
%{__autoconf}
%{__autoheader}
%{__automake}
%configure \
	CXXFLAGS="%{rpmcxxflags} -Wno-error"
%{__make}

%install
rm -rf $RPM_BUILD_ROOT
# create directories if necessary
#install -d $RPM_BUILD_ROOT

%{__make} install \
	DESTDIR=$RPM_BUILD_ROOT

%clean
rm -rf $RPM_BUILD_ROOT

%post	-p /sbin/ldconfig
%postun	-p /sbin/ldconfig

%files
%defattr(644,root,root,755)
# %doc AUTHORS CREDITS ChangeLog NEWS README THANKS TODO
%attr(755,root,root) %{_libdir}/libcassandra.so.*.*.*
%attr(755,root,root) %ghost %{_libdir}/libcassandra.so.2
%attr(755,root,root) %{_libdir}/libgenthrift.so.*.*.*
%attr(755,root,root) %ghost %{_libdir}/libgenthrift.so.0

%files devel
%defattr(644,root,root,755)
%{_libdir}/libcassandra.so
%{_libdir}/libcassandra.la
%{_libdir}/libgenthrift.so
%{_libdir}/libgenthrift.la
%{_includedir}/libcassandra
%{_includedir}/libgenthrift
